# Generated by Django 5.0.4 on 2024-04-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('trainer', 'Тренер'), ('admin', 'Админ')], max_length=10),
        ),
    ]
